# Usamos la imagen de Node.js
FROM node:16

# Directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Exponer el puerto que usará la aplicación
EXPOSE 3000

# Comando para correr la aplicación en modo producción
CMD ["npx", "serve", "build"]
